export const products = [
    {   
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/9.jpg",
        name: "SoundBox Pro Portable",
        price: 23,
        discount: 10,
        index: 1,
        type: "accessories",
        brand: "studio design",
    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/13.jpg",
        name: "Naham WiFi HD 1080",
        price: 23,
        index: 2,
        type: "accessories",
        brand: "studio design",
    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/11.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 3,
        type: "accessories",
        brand: "studio design",

    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 4,
        type: "accessories",
        brand: "studio design",

    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 5,
        type: "accessories",
        brand: "studio design",

    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 6,
        type: "phone",
        brand: "studio design",

    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 7,
        type: "phone",
        brand: "studio design",

    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 8,
        type: "phone",
        brand: "studio design",

    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 9,
        type: "phone",
        brand: "studio design",

    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 10,
        type: "phone",
        brand: "studio design",

    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 11,
        type: "laptop",
        brand: "studio design",

    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 12,
        type: "laptop",
        brand: "studio design",
    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 13,
        type: "laptop",
        brand: "studio design",

    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 14,
        type: "laptop",
        brand: "studio design",
    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 15,
        type: "laptop",
        brand: "studio design",
    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 16,
        type: "laptop",
        brand: "studio design",
    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 17,
        type: "component",
        brand: "studio design",
    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 18,
        type: "component",
        brand: "studio design",
    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 19,
        type: "component",
        brand: "studio design",
    },
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 20,
        type: "component",
        brand: "studio design",
    },    
    {
        thumbnail: "https://htmldemo.net/abelo/abelo/assets/images/product-image/17.jpg",
        name: "Polk Audio T30 Speaker",
        price: 23,
        index: 21,
        type: "component",
        brand: "studio design",
    },
]